name: CI

on:
  push:
    branches: ["main", "feature/juan"]
  pull_request:
    branches: ["main"]

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Compile Python files
        run: python -m py_compile src/run.py src/app/__init__.py src/app/db.py src/app/routes.py
